[2023-06-29 08:22:59,761] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: apartment_transaction_etl_dag.run_etl_task scheduled__2023-04-01T00:00:00+00:00 [queued]>
[2023-06-29 08:22:59,797] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: apartment_transaction_etl_dag.run_etl_task scheduled__2023-04-01T00:00:00+00:00 [queued]>
[2023-06-29 08:22:59,797] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2023-06-29 08:22:59,797] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2023-06-29 08:22:59,797] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2023-06-29 08:22:59,829] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): run_etl_task> on 2023-04-01 00:00:00+00:00
[2023-06-29 08:22:59,837] {standard_task_runner.py:52} INFO - Started process 89 to run task
[2023-06-29 08:22:59,848] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'apartment_transaction_etl_dag', 'run_etl_task', 'scheduled__2023-04-01T00:00:00+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/apartment_transaction_dag.py', '--cfg-path', '/tmp/tmpi2c933bf', '--error-file', '/tmp/tmpv1ujqvm2']
[2023-06-29 08:22:59,849] {standard_task_runner.py:77} INFO - Job 22: Subtask run_etl_task
[2023-06-29 08:22:59,968] {logging_mixin.py:109} INFO - Running <TaskInstance: apartment_transaction_etl_dag.run_etl_task scheduled__2023-04-01T00:00:00+00:00 [running]> on host d3599d0cd7b8
[2023-06-29 08:23:00,089] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=apartment_transaction_etl_dag
AIRFLOW_CTX_TASK_ID=run_etl_task
AIRFLOW_CTX_EXECUTION_DATE=2023-04-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-01T00:00:00+00:00
[2023-06-29 08:23:00,090] {logging_mixin.py:109} INFO - >>> Running 'etl' function. Logged at 2023-06-29 08:23:00.090819+00:00
[2023-06-29 08:23:00,091] {logging_mixin.py:109} INFO - >>> Running 'connect_db' function. Logged at 2023-06-29 08:23:00.090995+00:00
[2023-06-29 08:23:00,091] {logging_mixin.py:109} INFO - Connecting to DB
[2023-06-29 08:23:00,169] {logging_mixin.py:109} INFO - >>> Function: 'connect_db' executed. Logged at 2023-06-29 08:23:00.090995+00:00
[2023-06-29 08:23:00,169] {logging_mixin.py:109} INFO - >>> Running 'extract' function. Logged at 2023-06-29 08:23:00.169285+00:00
[2023-06-29 08:23:00,169] {logging_mixin.py:109} INFO - Reading dataset from https://gist.githubusercontent.com/mmphego/5b6fc4d6dc3c8fba4fce9d994a2fe16b/raw/ab5df0e76812e13df5b31e466a5fb787fac0599a/wine_quality.csv
[2023-06-29 08:23:01,568] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/apartment_transaction_dag.py", line 46, in wrapper
    to_execute = func(*args, **kwargs)
  File "/opt/airflow/dags/apartment_transaction_dag.py", line 165, in etl
    raw_df = extract(DATASET_URL)
  File "/opt/airflow/dags/apartment_transaction_dag.py", line 46, in wrapper
    to_execute = func(*args, **kwargs)
  File "/opt/airflow/dags/apartment_transaction_dag.py", line 116, in extract
    payload = "LAWD_CD=" + code + "&" + "DEAL_YMD=" + date + "&" + "serviceKey=" + CONFIG["SERVICE_KEY"] + "&"
NameError: name 'date' is not defined
[2023-06-29 08:23:01,694] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=apartment_transaction_etl_dag, task_id=run_etl_task, execution_date=20230401T000000, start_date=20230629T082259, end_date=20230629T082301
[2023-06-29 08:23:01,729] {standard_task_runner.py:92} ERROR - Failed to execute job 22 for task run_etl_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/apartment_transaction_dag.py", line 46, in wrapper
    to_execute = func(*args, **kwargs)
  File "/opt/airflow/dags/apartment_transaction_dag.py", line 165, in etl
    raw_df = extract(DATASET_URL)
  File "/opt/airflow/dags/apartment_transaction_dag.py", line 46, in wrapper
    to_execute = func(*args, **kwargs)
  File "/opt/airflow/dags/apartment_transaction_dag.py", line 116, in extract
    payload = "LAWD_CD=" + code + "&" + "DEAL_YMD=" + date + "&" + "serviceKey=" + CONFIG["SERVICE_KEY"] + "&"
NameError: name 'date' is not defined
[2023-06-29 08:23:01,831] {local_task_job.py:154} INFO - Task exited with return code 1
[2023-06-29 08:23:02,052] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-06-29 08:56:36,819] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: apartment_transaction_etl_dag.run_etl_task scheduled__2023-04-01T00:00:00+00:00 [queued]>
[2023-06-29 08:56:36,836] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: apartment_transaction_etl_dag.run_etl_task scheduled__2023-04-01T00:00:00+00:00 [queued]>
[2023-06-29 08:56:36,837] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2023-06-29 08:56:36,837] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2023-06-29 08:56:36,837] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2023-06-29 08:56:36,864] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): run_etl_task> on 2023-04-01 00:00:00+00:00
[2023-06-29 08:56:36,869] {standard_task_runner.py:52} INFO - Started process 1174 to run task
[2023-06-29 08:56:36,877] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'apartment_transaction_etl_dag', 'run_etl_task', 'scheduled__2023-04-01T00:00:00+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/apartment_transaction_dag.py', '--cfg-path', '/tmp/tmp10gp7878', '--error-file', '/tmp/tmpmssz8a33']
[2023-06-29 08:56:36,878] {standard_task_runner.py:77} INFO - Job 35: Subtask run_etl_task
[2023-06-29 08:56:36,976] {logging_mixin.py:109} INFO - Running <TaskInstance: apartment_transaction_etl_dag.run_etl_task scheduled__2023-04-01T00:00:00+00:00 [running]> on host d3599d0cd7b8
[2023-06-29 08:56:37,068] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=apartment_transaction_etl_dag
AIRFLOW_CTX_TASK_ID=run_etl_task
AIRFLOW_CTX_EXECUTION_DATE=2023-04-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-01T00:00:00+00:00
[2023-06-29 08:56:37,069] {logging_mixin.py:109} INFO - >>> Running 'etl' function. Logged at 2023-06-29 08:56:37.069791+00:00
[2023-06-29 08:56:37,069] {logging_mixin.py:109} INFO - >>> Running 'connect_db' function. Logged at 2023-06-29 08:56:37.069922+00:00
[2023-06-29 08:56:37,070] {logging_mixin.py:109} INFO - Connecting to DB
[2023-06-29 08:56:37,120] {logging_mixin.py:109} INFO - >>> Function: 'connect_db' executed. Logged at 2023-06-29 08:56:37.069922+00:00
[2023-06-29 08:56:37,120] {logging_mixin.py:109} INFO - >>> Running 'extract' function. Logged at 2023-06-29 08:56:37.120796+00:00
[2023-06-29 08:56:41,939] {logging_mixin.py:109} INFO - >>> Function: 'extract' executed. Logged at 2023-06-29 08:56:37.120796+00:00
[2023-06-29 08:56:41,939] {logging_mixin.py:109} INFO - >>> Running 'load_to_db' function. Logged at 2023-06-29 08:56:41.939827+00:00
[2023-06-29 08:56:41,939] {logging_mixin.py:109} INFO - Loading dataframe to DB on table: apartment_transaction_table
[2023-06-29 08:56:42,133] {logging_mixin.py:109} INFO - >>> Function: 'load_to_db' executed. Logged at 2023-06-29 08:56:41.939827+00:00
[2023-06-29 08:56:42,134] {logging_mixin.py:109} INFO - >>> Function: 'etl' executed. Logged at 2023-06-29 08:56:37.069791+00:00
[2023-06-29 08:56:42,134] {python.py:175} INFO - Done. Returned value was: None
[2023-06-29 08:56:42,152] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=apartment_transaction_etl_dag, task_id=run_etl_task, execution_date=20230401T000000, start_date=20230629T085636, end_date=20230629T085642
[2023-06-29 08:56:42,197] {local_task_job.py:154} INFO - Task exited with return code 0
[2023-06-29 08:56:42,252] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
